name: Manually trigger sync issue to Jira

# This workflow will be triggered manually
on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'A required input parameter'
        required: true
      optional-input:
        description: 'An optional input parameter'
        required: false


concurrency: jira_issues

jobs:
  sync_issues_to_jira:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync GitHub issues to Jira project
        uses: espressif/github-actions/sync_issues_to_jira@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: IDFSYNTEST
          JIRA_COMPONENT: Test Component
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
